---
# Run the checks here too, because preinstall skips them with ignore_assert_errors
- name: Calico | Run the pre-flight checks
  import_tasks: preflight.yml

- name: Calico | Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
  - files:
    - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] | lower | replace('/', '_') }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_release'] }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower | replace('/', '_') }}.yml"
    - "{{ ansible_facts['distribution'] | lower }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['architecture'] }}.yml"
    - "{{ ansible_facts['os_family'] | lower }}.yml"
    - defaults.yml
    paths:
    - ../vars
    skip: true
