---
policy:
  - section:
      - id: [os]
        block-list: []
        label:
          - name: 'RHEL 9'
            keys: ['RHEL 9']
          - name: 'RHEL 8'
            keys: ['RHEL 8']
          - name: 'Fedora 40'
            keys: ['Fedora 40']
          - name: 'Ubuntu 24'
            keys: ['Ubuntu 24']
          - name: 'Ubuntu 22'
            keys: ['Ubuntu 22']
          - name: 'Ubuntu 20'
            keys: ['Ubuntu 20']
          - name: 'Debian 12'
            keys: ['Debian 12']
          - name: 'Debian 11'
            keys: ['Debian 11']
          - name: 'Flatcar Container Linux'
            keys: ['Flatcar Container Linux']
          - name: 'openSUSE Leap'
            keys: ['openSUSE Leap']
          - name: 'openSUSE Tumbleweed'
            keys: ['openSUSE Tumbleweed']
          - name: 'Oracle Linux 9'
            keys: ['Oracle Linux 9']
          - name: 'Oracle Linux 8'
            keys: ['Oracle Linux 8']
          - name: 'AlmaLinux 9'
            keys: ['AlmaLinux 9']
          - name: 'AlmaLinux 8'
            keys: ['AlmaLinux 8']
          - name: 'Rocky Linux 9'
            keys: ['Rocky Linux 9']
          - name: 'Rocky Linux 8'
            keys: ['Rocky Linux 8']
          - name: 'Amazon Linux 2'
            keys: ['Amazon Linux 2']
          - name: 'Kylin Linux Advanced Server V10'
            keys: ['Kylin Linux Advanced Server V10']
          - name: 'UOS Linux 20'
            keys: ['UOS Linux 20']
          - name: 'openEuler 24'
            keys: ['openEuler 24']
          - name: 'openEuler 22'
            keys: ['openEuler 22']
          - name: 'openEuler 20'
            keys: ['openEuler 20']
          - name: 'Other|Unsupported'
            keys: ['Other|Unsupported']
