version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - release-note-none
    groups:
      molecule:
        patterns:
          - molecule
          - molecule-plugins*
    ignore:
      # Ansible major versions are upgraded manually to support multiple OS/Python versions.
      - dependency-name: "ansible"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - release-note-none
      - ci-short
    schedule:
      interval: "weekly"
