FROM python:3-slim
RUN apt-get update -y -qq \
    && apt-get install -y -qq --no-install-recommends \
    libssl-dev openssh-client sshpass apt-transport-https jq moreutils git \
    ca-certificates curl gnupg2 software-properties-common rsync \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /kubespray
COPY . .
RUN python3 -m pip -q install -r requirements.txt
RUN KUBE_VERSION=$(sed -n 's/^kube_version: //p' roles/kubespray-defaults/defaults/main.yaml) \
    && curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBE_VERSION/bin/linux/amd64/kubectl \
    && chmod a+x kubectl \
    && mv kubectl /usr/local/bin/kubectl

ENV LANG=C.UTF-8