---
resolved_images_to_load: "{{ (downloads | community.general.keep_keys(images_to_load)).values() | selectattr('enabled', 'all') }}"
oci_archive_src_path: "{{ install_source_localhost }}/images/{{ ansible_machine }}%{{ item.image_name | regex_replace('/', '%') }}.tar"
oci_archive_dest_path: "{{ local_release_dir }}/images/{{ item.image_name | regex_replace('/', '%') }}.tar"
