---
- name: CNI | make sure /opt/cni/bin exists
  file:
    path: /opt/cni/bin
    state: directory
    mode: "0755"
    owner: "{{ 'root' if (kube_network_plugin == 'cilium' or cilium_deploy_additionally) else cni_bin_owner }}"
    recurse: true

- name: CNI | Copy cni plugins
  unarchive:
    src: "{{ downloads.cni.dest }}"
    dest: "/opt/cni/bin"
    mode: "0755"
    owner: "{{ 'root' if (kube_network_plugin == 'cilium' or cilium_deploy_additionally) else cni_bin_owner }}"
    remote_src: true
