---
argument_specs:
  main:
    options:
      option-name: images_to_load
      description: List of images to be loaded into the container runtime.
      type: list
      elements: str
      required: true
