---
## Variables used by roles/download and task installing artefacts on node

# This variable is the default for local_release_dir and is used to refer to
# the default even when `local_release_dir` is overridden by inventory
default_local_release_dir: /tmp/releases
