---
# resolve variables across delegation
#
# this should point to the correct bin_dir in all contexts,
# but when not using delegation, prefers the usual bin_dir

# TODO: `vars` is deprecated and will be removed in ansible-core 2.24
# The alternative is way less readable though.
# Possible alternatives:
# - custom lookup plugin
_var_ns: "{{ hostvars[ansible_delegated_vars.keys()[0]] if ansible_delegated_vars is defined else vars }}"
delegated_bin_dir: "{{ _var_ns['bin_dir'] | d(default_bin_dir) }}"

# Reused for bin_dir, but needs to be a separate variable to allow
# inventory override without mangling delegated_bin_dir
default_bin_dir: "{{(
      '/usr/local/bin'
      if _var_ns['ansible_facts']['os_family'] != 'Flatcar'
      else '/opt/bin'
    )
    if _var_ns['ansible_facts']['user_id'] == (_var_ns['ansible_become_user'] | d('root'))
    else
      (_var_ns['ansible_facts']['env'].HOME + '/.local/bin')
}}"
# Internal version manipulation tooling

# Get kubernetes major version (i.e. 1.17.4 => 1.17)
kube_major_version: "{{ (kube_version | split('.'))[:-1] | join('.') }}"
kube_next: "{{ ((kube_version | split('.'))[1] | int) + 1 }}"
kube_major_next_version: "1.{{ kube_next }}"

pod_infra_supported_versions:
  '1.36': '3.10.2'
  '1.35': '3.10.1'
  '1.34': '3.10.1'

etcd_supported_versions:
  '1.36': "{{ (etcd_binary_checksums['amd64'].keys() | select('version', '3.7', '<'))[0] }}"
  '1.35': "{{ (etcd_binary_checksums['amd64'].keys() | select('version', '3.7', '<'))[0] }}"
  '1.34': "{{ (etcd_binary_checksums['amd64'].keys() | select('version', '3.6', '<'))[0] }}"

# Kubespray constants

kube_proxy_deployed: "{{ 'addon/kube-proxy' not in kubeadm_init_phases_skip }}"

# The lowest version allowed to upgrade from (same as calico_version in the previous branch)
calico_min_version_required: "3.27.0"

containerd_min_version_required: "1.3.7"

# mixed kube_service_addresses/kube_service_addresses_ipv6 for a variety of network stacks(dualstack, ipv6only, ipv4only)
kube_service_subnets: >-
  {%- if ipv4_stack and ipv6_stack -%}
  {{ kube_service_addresses }},{{ kube_service_addresses_ipv6 }}
  {%- elif ipv4_stack -%}
  {{ kube_service_addresses }}
  {%- else -%}
  {{ kube_service_addresses_ipv6 }}
  {%- endif -%}

# mixed kube_pods_subnet/kube_pods_subnet_ipv6 for a variety of network stacks(dualstack, ipv6only, ipv4only)
kube_pods_subnets: >-
  {%- if ipv4_stack and ipv6_stack -%}
  {{ kube_pods_subnet }},{{ kube_pods_subnet_ipv6 }}
  {%- elif ipv4_stack -%}
  {{ kube_pods_subnet }}
  {%- else -%}
  {{ kube_pods_subnet_ipv6 }}
  {%- endif -%}
