---

manila_csi_provisioner_image_tag: "v5.3.0"
manila_csi_snapshotter_image_tag: "v8.4.0"
manila_csi_resizer_image_tag: "v1.14.0"
manila_csi_livenessprobe_image_tag: "v2.12.0"

# CEPHFS is used by default; NFS is supported by Manila but untested
manila_share_protocol: "CEPHFS"

manila_fwd_driver_name: "cephfs.csi.ceph.com"
manila_fwd_endpoint: "unix:///var/lib/kubelet/plugins/{{ manila_fwd_driver_name }}/csi.sock"
manila_fwd_plugin_dir: "/var/lib/kubelet/plugins/{{ manila_fwd_driver_name }}"

manila_csi_controller_replicas: 2
manila_csi_health_port: 9809

cephfs_csi_image_repo: "quay.io/cephcsi/cephcsi"
cephfs_csi_image_tag: "v3.11.0"

# To access Manila, the CSI controller will need credentials to access
# openstack apis. Per default this values will be
# read from the environment.
manila_auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
manila_username: "{{ lookup('env', 'OS_USERNAME') }}"
manila_password: "{{ lookup('env', 'OS_PASSWORD') }}"
manila_application_credential_id: "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_ID') }}"
manila_application_credential_name: "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_NAME') }}"
manila_application_credential_secret: "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_SECRET') }}"
manila_region: "{{ lookup('env', 'OS_REGION_NAME') }}"
manila_tenant_id: "{{ lookup('env', 'OS_TENANT_ID') | default(lookup('env', 'OS_PROJECT_ID'), true) }}"
manila_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') | default(lookup('env', 'OS_PROJECT_NAME'), true) }}"
manila_domain_name: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') }}"
manila_domain_id: "{{ lookup('env', 'OS_USER_DOMAIN_ID') }}"
manila_project_domain_name: "{{ lookup('env', 'OS_PROJECT_DOMAIN_NAME') }}"
manila_cacert: "{{ lookup('env', 'OS_CACERT') }}"

manila_log_level: 5

## Dictionaries of extra arguments to add to the Manila CSI plugin containers
## Format:
##  manila_csi_attacher_extra_args:
##    arg1: "value1"
##    arg2: "value2"
manila_csi_provisioner_extra_args: {}
