---
pipeline-image:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - image-cache
  tags:
    - ffci
  stage: build
  image: moby/buildkit:rootless
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
    CACHE_IMAGE: $CI_REGISTRY_IMAGE/pipeline:cache
  # NOTE: The override is required because the default Kaniko image does NOT include any shell (not even /bin/sh),
  # but the pipeline needs a shell to run scripts like rebase.sh. If the pipeline is refactored to remove the need for shell scripts,
  # or if a debug image with a shell is used, this override can be removed. See https://github.com/GoogleContainerTools/kaniko for details.
  before_script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > ~/.docker/config.json
  script:
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=$CI_PROJECT_DIR \
        --local dockerfile=$CI_PROJECT_DIR \
        --opt filename=pipeline.Dockerfile \
        --export-cache type=registry,ref=$CACHE_IMAGE \
        --import-cache type=registry,ref=$CACHE_IMAGE \
        --output type=image,name=$PIPELINE_IMAGE,push=true
