---
manila_storage_classes:
  - name: manila-csi
    is_default: false
    parameters:
      type: "cephfsnative"
      protocol: "cephfs"
      backend: "cephfs"
      csi.storage.k8s.io/provisioner-secret-name: "csi-manila-secrets"
      csi.storage.k8s.io/provisioner-secret-namespace: "kube-system"
      csi.storage.k8s.io/node-publish-secret-name: "csi-manila-secrets"
      csi.storage.k8s.io/node-publish-secret-namespace: "kube-system"
      csi.storage.k8s.io/node-stage-secret-name: "csi-manila-secrets"
      csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
      csi.storage.k8s.io/controller-expand-secret-name: "csi-manila-secrets"
      csi.storage.k8s.io/controller-expand-secret-namespace: "kube-system"
