---
- name: Normalize ansible_facts for redhat-family extensions
  set_fact:
    ansible_facts: >-
      {{ ansible_facts | combine({
           'os_family': 'RedHat',
           'distribution_major_version': '8'
         }) }}
  when: ansible_facts['distribution'] in redhat_os_family_extensions
  tags:
    - facts

- name: Normalize ansible_facts for openSUSE MicroOS
  set_fact:
    ansible_facts: "{{ ansible_facts | combine({'os_family': 'Suse'}) }}"
    ansible_os_family: Suse
  when: ansible_facts['distribution'] == "openSUSE MicroOS"
  tags:
    - facts

- name: NetworkManager | Check if host has NetworkManager
  # noqa command-instead-of-module - Should we use service_facts for this?
  command: systemctl is-active --quiet NetworkManager.service
  register: networkmanager_enabled
  failed_when: false
  changed_when: false
  check_mode: false

- name: Set etcd vars if using kubeadm mode
  set_fact:
    etcd_cert_dir: "{{ kube_cert_dir }}"
    kube_etcd_cacert_file: "etcd/ca.crt"
    kube_etcd_cert_file: "apiserver-etcd-client.crt"
    kube_etcd_key_file: "apiserver-etcd-client.key"
  when:
    - etcd_deployment_type == "kubeadm"

- name: Check /usr readonly
  stat:
    path: "/usr"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: usr

- name: Set alternate flexvolume path
  set_fact:
    kubelet_flexvolumes_plugins_dir: /var/lib/kubelet/volumeplugins
  when: not usr.stat.writeable
