---
# Disable swap
- name: Disable swap
  import_tasks: 0010-swapoff.yml
  when:
    - kubelet_fail_swap_on

- name: Set facts
  import_tasks: 0020-set_facts.yml
  tags:
    - facts

- name: Check settings
  import_tasks: 0040-verify-settings.yml
  tags:
    - asserts

- name: Create directories
  import_tasks: 0050-create_directories.yml

- name: Apply networkmanager unmanaged devices settings
  import_tasks: 0062-networkmanager-unmanaged-devices.yml
  when:
    - networkmanager_enabled.rc == 0
  tags:
    - bootstrap_os

- name: Apply system configurations
  import_tasks: 0080-system-configurations.yml
  tags:
    - bootstrap_os

- name: Configure NTP
  import_tasks: 0081-ntp-configurations.yml
  when:
    - ntp_enabled
  tags:
    - bootstrap_os

- name: Check if we are running inside a Azure VM
  stat:
    path: /var/lib/waagent/
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: azure_check
  tags:
    - bootstrap_os

- name: Run calico checks
  include_role:
    name: network_plugin/calico
    tasks_from: check
  when:
    - kube_network_plugin == 'calico'
    - not ignore_assert_errors
