---
- name: Preinstall | reload NetworkManager
  service:
    name: NetworkManager.service
    state: restarted

- name: Preinstall | restart ntp
  service:
    name: "{{ ntp_service_name }}"
    state: restarted
  when: ntp_enabled
