---
external_oci_auth_use_instance_principals: false
external_oci_load_balancer_security_list_management_mode: All
external_oci_load_balancer_security_lists: {}

external_oci_ratelimiter_qps_read: 20.0
external_oci_ratelimiter_bucket_read: 5
external_oci_ratelimiter_qps_write: 20.0
external_oci_ratelimiter_bucket_write: 5

external_oci_cloud_controller_image_repo: ghcr.io/oracle/cloud-provider-oci
external_oci_cloud_controller_image_tag: "v1.29.0"
