---
# All members must run etcd 3.6.11 or later before the upgrade to 3.7.
# https://etcd.io/docs/v3.7/upgrades/upgrade_3_7/
- name: Ensure etcd version is >=3.6.11 before upgrade to 3.7
  when:
    - etcd_cluster_setup
    - etcd_current_version != ''
    - etcd_current_version is version('3.6.11', '<')
    - etcd_version is version('3.7.0', '>=')
  fail:
    msg: "You need to upgrade etcd to 3.6.11 or later before upgrade to 3.7. Current version is {{ etcd_current_version }}."
