---

timeout: 7200s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20260205-38cfa9523f
    args:
      - bash
      - -ceu
      - |
        apk add --no-cache ansible-core qemu-img
        ansible-galaxy collection install community.general -p /usr/share/ansible/collections
        make -C test-infra/image-builder push-single-staging \
          image_name=ubuntu-2404 \
          staging_registry=us-central1-docker.pkg.dev/$PROJECT_ID/kubespray
substitutions:
  _PULL_BASE_REF: "master"
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/kubespray/vm-ubuntu-2404:latest
