---
- name: Youki | Install youki binary
  copy:
    src: "{{ local_release_dir }}/{{ (downloads.youki.dest | splitext)[0] }}/youki"
    dest: "{{ youki_bin_dir }}/youki"
    mode: "0755"
    remote_src: "{{ download_delegate == inventory_hostname }}"
