---
- name: Gateway API | Download YAML
  include_tasks: "../../../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.gateway_api_crds) }}"

- name: Gateway API | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/gateway_api"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Gateway API | Copy YAML from download dir
  copy:
    src: "{{ local_release_dir }}/gateway-api-{{ gateway_api_channel }}-install.yaml"
    dest: "{{ kube_config_dir }}/addons/gateway_api/{{ gateway_api_channel }}-install.yaml"
    mode: "0644"
    remote_src: true
  when:
    - "inventory_hostname == groups['kube_control_plane'][0]"

- name: Gateway API | Install Gateway API
  command:
    cmd: >-
      {{ bin_dir }}/kubectl apply
      --server-side={{ server_side_apply | default(false) | lower }}
      --filename={{ kube_config_dir }}/addons/gateway_api/{{ gateway_api_channel }}-install.yaml
  when:
    - "inventory_hostname == groups['kube_control_plane'][0]"
  register: gateway_api_apply
  retries: 3
  delay: 5
  until: gateway_api_apply is succeeded
  changed_when:
    - "' configured' in gateway_api_apply.stdout
       or ' created' in gateway_api_apply.stdout
       or ' serverside-applied' in gateway_api_apply.stdout"
