---
- name: Validate container engine
  include_role:
    name: container-engine/validate-container-engine
    apply:
      tags:
        - container-engine
        - validate-container-engine
  tags:
    - container-engine
    - validate-container-engine

- name: Kata Containers
  include_role:
    name: container-engine/kata-containers
    apply:
      tags:
        - container-engine
        - kata-containers
  when:
    - kata_containers_enabled
  tags:
    - container-engine
    - kata-containers

- name: gVisor
  include_role:
    name: container-engine/gvisor
    apply:
      tags:
        - container-engine
        - gvisor
  when:
    - gvisor_enabled
    - container_manager in ['docker', 'containerd']
  tags:
    - container-engine
    - gvisor

- name: crun
  include_role:
    name: container-engine/crun
    apply:
      tags:
        - container-engine
        - crun
  when:
    - crun_enabled
  tags:
    - container-engine
    - crun

- name: youki
  include_role:
    name: container-engine/youki
    apply:
      tags:
        - container-engine
        - youki
  when:
    - youki_enabled
    - container_manager == 'crio'
  tags:
    - container-engine
    - youki

- name: cri-o
  include_role:
    name: container-engine/cri-o
    apply:
      tags:
        - container-engine
        - crio
  when:
    - container_manager == 'crio'
  tags:
    - container-engine
    - crio

- name: containerd
  include_role:
    name: container-engine/containerd
    apply:
      tags:
        - container-engine
        - containerd
  when:
    - container_manager == 'containerd'
  tags:
    - container-engine
    - containerd

- name: cri-dockerd
  include_role:
    name: container-engine/cri-dockerd
    apply:
      tags:
        - container-engine
        - docker
  when:
    - container_manager == 'docker'
  tags:
    - container-engine
    - docker
