---
- name: Check that localhost is present in the play
  assert:
    that: ('localhost' in ansible_play_hosts_all)
    fail_msg: >
      Kubespray needs to include 'localhost' when downloading binaries or container images,
      as the Ansible controller is either the downloader or the 'transit' node.
      Please append ':localhost' to your limit string.
