# Arhitectures and OSes
architectures = ['arm', 'arm64', 'amd64', 'ppc64le']
oses = ['darwin', 'linux', 'windows']

# Paths
path_download = 'roles/kubespray-defaults/defaults/main/download.yml'
path_checksum = 'roles/kubespray-defaults/defaults/main/checksums.yml'
path_main = 'roles/kubespray-defaults/defaults/main/main.yml'
path_readme = 'README.md'
path_version_diff = 'version_diff.json'


component_info = {
    'calico_crds': {
        'owner': 'projectcalico',
        'repo': 'calico',
        'url_download': 'https://github.com/projectcalico/calico/archive/VERSION.tar.gz',
        'placeholder_version': ['calico_version'],
        'placeholder_checksum' : 'calico_crds_archive_checksums',
        'checksum_structure' : 'simple',
        'release_type' : 'release',
        },
    'calicoctl': {
        'owner': 'projectcalico',
        'repo': 'calico',
        'url_download': 'https://github.com/projectcalico/calico/releases/download/VERSION/calicoctl-linux-ARCH',
        'placeholder_version': ['calico_version'],
        'placeholder_checksum' : 'calicoctl_binary_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'ciliumcli': {
        'owner': 'cilium',
        'repo': 'cilium-cli',
        'url_download': 'https://github.com/cilium/cilium-cli/releases/download/VERSION/cilium-linux-ARCH.tar.gz.sha256sum',
        'placeholder_version': ['cilium_cli_version'],
        'placeholder_checksum' : 'ciliumcli_binary_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'cni': {
        'owner': 'containernetworking',
        'repo': 'plugins',
        'url_download': 'https://github.com/containernetworking/plugins/releases/download/VERSION/cni-plugins-linux-ARCH-VERSION.tgz.sha256',
        'placeholder_version': ['cni_version'],
        'placeholder_checksum' : 'cni_binary_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'containerd': {
        'owner': 'containerd',
        'repo': 'containerd',
        'url_download': 'https://github.com/containerd/containerd/releases/download/vVERSION/containerd-VERSION-linux-ARCH.tar.gz.sha256sum',
        'placeholder_version': ['containerd_version'],
        'placeholder_checksum' : 'containerd_archive_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'crictl': {
        'owner': 'kubernetes-sigs',
        'repo': 'cri-tools',
        'url_download': 'https://github.com/kubernetes-sigs/cri-tools/releases/download/VERSION/crictl-VERSION-linux-ARCH.tar.gz.sha256',
        'placeholder_version': ['crictl_supported_versions', 'kube_major_version'],
        'placeholder_checksum' : 'crictl_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'cri_dockerd': {
        'owner': 'Mirantis',
        'repo': 'cri-dockerd',
        'url_download': 'https://github.com/Mirantis/cri-dockerd/releases/download/vVERSION/cri-dockerd-VERSION.ARCH.tgz',
        'placeholder_version': ['cri_dockerd_version'],
        'placeholder_checksum' : 'cri_dockerd_archive_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'crio': {
        'owner': 'cri-o',
        'repo': 'cri-o',
        'url_download': 'https://storage.googleapis.com/cri-o/artifacts/cri-o.ARCH.VERSION.tar.gz',
        'placeholder_version': ['crio_supported_versions', 'kube_major_version'],
        'placeholder_checksum' : 'crio_archive_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'crun': {
        'owner': 'containers',
        'repo': 'crun',
        'url_download': 'https://github.com/containers/crun/releases/download/VERSION/crun-VERSION-linux-ARCH',
        'placeholder_version': ['crun_version'],
        'placeholder_checksum' : 'crun_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'etcd': {
        'owner': 'etcd-io',
        'repo': 'etcd',
        'url_download': 'https://github.com/etcd-io/etcd/releases/download/VERSION/SHA256SUMS',
        'placeholder_version': ['etcd_supported_versions', 'kube_major_version'],
        'placeholder_checksum' : 'etcd_binary_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'gvisor_containerd_shim': {
        'owner': 'google',
        'repo': 'gvisor',
        'url_download': 'https://storage.googleapis.com/gvisor/releases/release/VERSION/ARCH/containerd-shim-runsc-v1',
        'placeholder_version': ['gvisor_version'],
        'placeholder_checksum' : 'gvisor_containerd_shim_binary_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'tag',
        },
    'gvisor_runsc': {
        'owner': 'google',
        'repo': 'gvisor',
        'url_download': 'https://storage.googleapis.com/gvisor/releases/release/VERSION/ARCH/runsc',
        'placeholder_version': ['gvisor_version'],
        'placeholder_checksum' : 'gvisor_runsc_binary_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'tag',
        },
    'helm': {
        'owner': 'helm',
        'repo': 'helm',
        'url_download': 'https://get.helm.sh/helm-VERSION-linux-ARCH.tar.gz',
        'placeholder_version': ['helm_version'],
        'placeholder_checksum' : 'helm_archive_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },

    'kata_containers': {
        'owner': 'kata-containers',
        'repo': 'kata-containers',
        'url_download': 'https://github.com/kata-containers/kata-containers/releases/download/VERSION/kata-static-VERSION-ARCH.tar.xz',
        'placeholder_version': ['kata_containers_version'],
        'placeholder_checksum' : 'kata_containers_binary_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'krew': {
        'owner': 'kubernetes-sigs',
        'repo': 'krew',
        'url_download': 'https://github.com/kubernetes-sigs/krew/releases/download/VERSION/krew-OS_ARCH.tar.gz.sha256',
        'placeholder_version': ['krew_version'],
        'placeholder_checksum' : 'krew_archive_checksums',
        'checksum_structure' : 'os_arch',
        'release_type' : 'release',
        },
    'kubeadm': {
        'owner': 'kubernetes',
        'repo': 'kubernetes',
        'url_download': 'https://dl.k8s.io/release/VERSION/bin/linux/ARCH/kubeadm.sha256',
        'placeholder_version': ['kube_version'],
        'placeholder_checksum' : 'kubeadm_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'kubectl': {
        'owner': 'kubernetes',
        'repo': 'kubernetes',
        'url_download': 'https://dl.k8s.io/release/VERSION/bin/linux/ARCH/kubectl.sha256',
        'placeholder_version': ['kube_version'],
        'placeholder_checksum' : 'kubectl_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'kubelet': {
        'owner': 'kubernetes',
        'repo': 'kubernetes',
        'url_download': 'https://dl.k8s.io/release/VERSION/bin/linux/ARCH/kubelet.sha256',
        'placeholder_version': ['kube_version'],
        'placeholder_checksum' : 'kubelet_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'nerdctl': {
        'owner': 'containerd',
        'repo': 'nerdctl',
        'url_download': 'https://github.com/containerd/nerdctl/releases/download/vVERSION/SHA256SUMS',
        'placeholder_version': ['nerdctl_version'],
        'placeholder_checksum' : 'nerdctl_archive_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'runc': {
        'owner': 'opencontainers',
        'repo': 'runc',
        'url_download': 'https://github.com/opencontainers/runc/releases/download/VERSION/runc.ARCH',
        'placeholder_version': ['runc_version'],
        'placeholder_checksum' : 'runc_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'skopeo': {
        'owner': 'containers',
        'repo': 'skopeo',
        'url_download': 'https://github.com/lework/skopeo-binary/releases/download/VERSION/skopeo-linux-ARCH',
        'placeholder_version': ['skopeo_version'],
        'placeholder_checksum' : 'skopeo_binary_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'youki': {
        'owner': 'containers',
        'repo': 'youki',
        'url_download': 'https://github.com/containers/youki/releases/download/vVERSION/youki-VERSION-ARCH.tar.gz',
        'placeholder_version': ['youki_version'],
        'placeholder_checksum' : 'youki_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
    'yq': {
        'owner': 'mikefarah',
        'repo': 'yq',
        'url_download': 'https://github.com/mikefarah/yq/releases/download/VERSION/checksums-bsd',
        'placeholder_version': ['yq_version'],
        'placeholder_checksum' : 'yq_checksums',
        'checksum_structure' : 'arch',
        'release_type' : 'release',
        },
}
