---
- name: Get kubeadm_images definition
  import_role:
    name: download/kubeadm_images

- name: Get images present on each nodes from Kubernetes API
  register: nodes_images
  run_once: true
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  failed_when:
    - nodes_images is failed
    - not ('No such file' in nodes_images.msg) # kubectl not installed
    - not ('The connection to the server' in nodes_images.stderr) # API server not running
  changed_when: false
  command:
    cmd: "{{ kubectl }} get nodes --output go-template-file=/dev/stdin"
    # go-template to get the following json, for all cluster nodes
    # {
    #   "some_node": [
    #     "some_image:some_tag",
    #     "some_image:some_other_tag",
    #     "some_image@some_hash",
    #     "some_image2:some_other_tag",
    #     ...
    #   ],
    #   "some_other_node": [
    #   ...
    #   ],
    #   ...
    # }
    # https://github.com/ansible/ansible-lint/issues/4647
    # noqa: jinja[invalid]
    stdin: !unsafe '
      { {{ range $n, $node := .items }}
        {{ if $n }},{{ end }}"{{ .metadata.name }}":
          [{{ range $i, $image := .status.images }}
            {{ if $i }},{{end}}
              {{ range $j, $name := .names }}
                {{ if $j}},{{end}}"{{ $name }}"
              {{ end }}
           {{ end }}]
        {{ end }} }'

- name: Compute missing images on each node - with architecture prefix
  vars:
    current_images: "{{ (nodes_images.stdout | d('{}', true) | from_json).get(inventory_hostname, []) }}"
    # Default filter handle the cluster setup case (no images on nodes)
    # To handle scale cases we also need a default for individual nodes, hence the .get()

  # TODO: separate downloads with container true into a different top-level
  # var to avoid the select overhead (runtime *AND* mental)
  # will also avoid the etcd / etcd_container confusion
  set_fact:
    images_to_pull: "{{
      downloads | combine(kubeadm_images) | dict2items |
      selectattr('value.container', 'defined') | selectattr('value.container') | selectattr('value.enabled', 'all') |
      map(attribute='value.image_name') | difference(current_images) |
      map('regex_replace', '^', host_architecture + '%')
    }}"

# - name: Find existing downloaded images on downloader nodes
#   find:
#     file_type: directory
#     depth: 5
#     recurse: true
#     paths:
#       - "{{ local_release_dir }}/images"
#   when: ('download_delegate_' + inventory_hostname) in groups

- name: Compute once the set of image delegated to localhost
  set_fact:
    images_to_pull_delegated_localhost: "{{
      groups['download_delegate_localhost'] | d([]) |
      map('extract', hostvars, morekeys=['images_to_pull']) |
      flatten | unique }}"
  run_once: true

- name: Download and fetch images
  vars:
    images_to_pull_delegated: "{{
      images_to_pull_delegated_localhost
      if inventory_hostname == 'localhost'
      else
      groups['download_delegate_' + inventory_hostname] | d([]) |
      map('extract', hostvars, morekeys=['images_to_pull']) |
      flatten | unique }}"
      # |
      # difference(existing_images.files | map(attribute='path') |
      # map('relpath', local_release_dir + '/images')) |
      # TODO: Is pre-checking the image here worth it or should we just relies on `creates:` on the next task ?
      # (which is simpler)
    oci_archive_path: "{{ local_release_dir }}/images/{{ arch_image_name | replace(':', '%25') | replace('/', '%2A') }}.tar"
    # Replace '/' to have flat file path (no need to create directory) and ':' to not mess with skopeo separator

  block:
    - name: Download images as OCI archives
      # TODO: handle image ref with digest as well as tags
      loop: "{{ images_to_pull_delegated }}"
      loop_control:
        loop_var: arch_image_name
      vars:
        image_name: "{{ (arch_image_name | split('%'))[1] }}"
        image_arch: "{{ (arch_image_name | split('%'))[0] }}"
      command:
        cmd: "{{ bin_dir }}/skopeo --insecure-policy --override-arch {{ image_arch }} copy docker://{{ image_name }} oci-archive:{{ oci_archive_path }}:{{ image_name }}"
        creates: "{{ oci_archive_path }}"

    # See 'Download_file | Fetch file to localhost' in download/file/tasks/main.yml for the logic (which is the same)
    # TODO: see if it can be refactored in common logic
    - name: Fetch OCI archives to localhost
      fetch:
        flat: true
        src: "{{ oci_archive_path }}"
        dest: "{{ install_source_localhost }}/images/"
      loop_control:
        loop_var: arch_image_name
      loop: "{{
        (images_to_pull_delegated | difference(images_to_pull_delegated_localhost))
        if (groups['download_delegate_' + inventory_hostname] | d([]) |
            difference([inventory_hostname]) != [])
        else
          []
        }}"
