---
nameservers: []
cloud_resolver: []
disable_host_nameservers: false
# DNS resolver option timeout and retry attempts.
dns_timeout: 2
dns_attempts: 2

# Set to false to disable the backup parameter, set to true to accumulate backups of config files.
leave_etc_backup_files: true

# Remove default cluster search domains (``default.svc.{{ dns_domain }}, svc.{{ dns_domain }}``).
remove_default_searchdomains: false

# Flatcar Container Linux by Kinvolk cloud init config file to define /etc/resolv.conf content
# for hostnet pods and infra needs
resolveconf_cloud_init_conf: /etc/resolveconf_cloud_init.conf

# Sets DNSStubListener=no, useful if you get "0.0.0.0:53: bind: address already in use"
systemd_resolved_disable_stub_listener: "{{ ansible_facts['os_family'] == 'Flatcar' }}"
