---
- name: Container Network Interface plugin
  include_role:
    name: network_plugin/cni
  when: kube_network_plugin != 'none'

- name: Cilium
  include_role:
    name: network_plugin/cilium
    apply:
      tags:
        - cilium
  when: kube_network_plugin == 'cilium' or cilium_deploy_additionally
  tags:
    - cilium

- name: Calico
  include_role:
    name: network_plugin/calico
    apply:
      tags:
        - calico
  when: kube_network_plugin == 'calico'
  tags:
    - calico

- name: Flannel
  include_role:
    name: network_plugin/flannel
    apply:
      tags:
        - flannel
  when: kube_network_plugin == 'flannel'
  tags:
    - flannel

- name: Macvlan
  include_role:
    name: network_plugin/macvlan
    apply:
      tags:
        - macvlan
  when: kube_network_plugin == 'macvlan'
  tags:
    - macvlan

- name: Kube-OVN
  include_role:
    name: network_plugin/kube-ovn
    apply:
      tags:
        - kube-ovn
  when: kube_network_plugin == 'kube-ovn'
  tags:
    - kube-ovn

- name: Kube-Router
  include_role:
    name: network_plugin/kube-router
    apply:
      tags:
        - kube-router
  when: kube_network_plugin == 'kube-router'
  tags:
    - kube-router

- name: Custom CNI
  include_role:
    name: network_plugin/custom_cni
    apply:
      tags:
        - custom_cni
  when: kube_network_plugin == 'custom_cni'
  tags:
    - custom_cni

- name: Multus
  include_role:
    name: network_plugin/multus
    apply:
      tags:
        - multus
  when: kube_network_plugin_multus
  tags:
    - multus
