---
- name: Set role and inventory node taint to empty list
  set_fact:
    role_node_taints: []
    inventory_node_taints: []

- name: Set master node taint
  set_fact:
    role_node_taints: "{{ role_node_taints + ['node-role.kubernetes.io/master:NoSchedule'] }}"
  when:
    - inventory_hostname in groups['kube_control_plane']
    - kube_node_taint_master|default(true)

- name: Set node_taints for nvidia gpu nodes
  set_fact:
    role_node_taints: "{{ role_node_taints + ['nvidia.com/gpu=:NoSchedule'] }}"
  when:
    - inventory_hostname in groups['kube_node']
    - kube_node_taint_nvidia_gpu|default(false)

- debug:  # noqa name[missing]
    var: role_node_taints
- debug:  # noqa name[missing]
    var: inventory_node_taints

- name: Taint nodes
  command: >-
    {{ kubectl }} taint node {{ kube_override_hostname | default(inventory_hostname) }} {{ (role_node_taints + node_taints) | join(' ') }} --overwrite=true
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  when:
    - (role_node_taints + node_taints) | length > 0
  tags:
    - node-taint
