name: "Check Broken Links"
on:
    merge_group:
    pull_request:
        branches:
            - master
jobs:
    linkchecker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Link Checker
              uses: lycheeverse/lychee-action@v2
              with:
                  fail: true
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
